# Site settings
title: Sandro Gallina
description: It is just a page about me, nothing more...
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://sandrogallina.com" 

# User settings
username: Sandro Gallina
user_description: Just a designer that started to work with web stuff...
user_title: Web Developer
email: sandro_gallina@hotmail.com
twitter_username: menphys
github_username:  sg1984
linkedin_username:  sandro-gallina
facebook_username:  sandro.gallina.9

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
